#全局端口定义server:
# 全局字符集设置
#不影响，程序不报错，不用理
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  aop:
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: utf-8

